language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
before_script:
  - git clone https://github.com/also/clojurescript.test.git --branch node --depth 1
  - cd clojurescript.test
  - lein2 cljsbuild once
  - cd ..
script:
  - cd clojurescript.test
  - ../command.js target/cljs/unoptimized target/cljs/unoptimized.js -a -m cemerick.cljs.node.runner "this.literal_js_was_evaluated = true" test/cemerick/cljs/test/extra_test_command_file.js
  - ../command.js target/cljs/whitespace.js -m cemerick.cljs.node.runner "this.literal_js_was_evaluated = true" test/cemerick/cljs/test/extra_test_command_file.js
  - ../command.js target/cljs/simple.js -m cemerick.cljs.node.runner "this.literal_js_was_evaluated = true" test/cemerick/cljs/test/extra_test_command_file.js
  - ../command.js target/cljs/advanced.js -m cemerick.cljs.node.runner "this.literal_js_was_evaluated = true" test/cemerick/cljs/test/extra_test_command_file.js
